spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/station_db?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
#    username: root
#    password: mbxl&mltmxm1
##    password: test1234
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.56.31:30001/demo?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: mysql520
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace